### ISSUE TITLE
The right way to build React apps

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [ericelliott/react-hello#1]
Great post Eric. I completely agree with you when it comes to 'bad advice' and building React Components. There is, however, no standard. Which can, at times, be a good thing as it allows developers the freedom to build React components as they see fit. However, I have proposed that there should be a 'recommended' approach to building React components and I think this example is fitting.

One proposed change to your example would be to use ES6 modules as opposed to Browserify. What do you think? I can help contribute and submit a PR if you are interested. Also the link to your book is throwing a 404.

**Comment by ericelliott** [comment]
I'm not sure what you mean. The Hello component **is an ES6 module**. Do you mean transform to a Node style module instead? The advantage of Browserify is that it creates a UMD that is both an AMD / standalone module in browsers _AND_ a valid node style module that you can use as you would any other module in any Node program.
